### ISSUE TITLE
How to effectively handle a server sleep?

### ISSUE THREAD

**Issue by Enzo-PsK** [slackapi/python-slack-events-api#101]
### Description

Hello guys! I searched and tried some workarounds, including a script to don't let the server in sleep mode, but I really want this to work in the right way. The issue is that I receive three messages when I send an event to my flask server when it is on sleep mode. I've faced this on Heroku, now on Render. And that makes me wonder if there is a way to solve this problem for good.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:
slackeventsapi version: 3.0.1
python version: 3.7
OS version(s):

#### Steps to reproduce:

1. Let the app sleep on Heroku or Render free plans (now only using in Render)
2. Send a message in slack to generate an event to the server
3. Wait for the response

#### Expected result:

I expect to receive only one response from the server.

#### Actual result:

Several messages are returned from the server.

**Comment by seratch** [comment]
Hi @Enzo-PsK, unfortunately there is no great solution for it. Your Flask app must always respond within 3 seconds. The only solution is to upgrade to any of paid plans to keep your app running 24/7.
