### ISSUE TITLE
Unable to cross `url_verification` phase in Event Request URL setup

### ISSUE THREAD

**Issue by sinchanroy** [slackapi/python-slack-events-api#104]
### Description

unable to cross url_verification phase in slack.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version: 3.0.1
python version: 3.8
OS version(s): Mac 13

#### Steps to reproduce:

Follow the steps as mentioned in Readme

#### Expected result:

App Events is verified in Slack

#### Actual result:

```
Our Request:
POST
"body": { 
	 "type": "url_verification",
	 "token": "",
	 "challenge": ""
}
Your Response:
"code": 
"error": "challenge_failed"
"body": {
  
}
```

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

![Screenshot 2023-04-25 at 12 05 53](https://user-images.githubusercontent.com/18273657/234244618-228c3164-0962-4617-af55-981053fabd2d.png)

**Comment by srajiang** [comment]
Hi @sinchanroy - Can you please provide some more information about how your application is handling the inbound verification request from Slack? When you are setting up Event Request URL, your app must verify the validity of the request from Slack (using the Signing Secret available in your apps Basic) return a 200 OK and the value of the challenge. 

Here's more information about handling the `url_verification` event: https://api.slack.com/events/url_verification

**Comment by seratch** [comment]
@sinchanroy If you're trying to configure the app with `endpoint="/slack/events"` like README does, you need to pass `https://{domain}/slack/events` instead.

**Comment by srajiang** [comment]
@sinchanroy Can you please give what @seratch suggested a try (adding /slack/events) to the end of your request URL domain in the Event Request URL UI, and let us know if that resolves your issue?
