### ISSUE TITLE
Slack Events API is showing verified for older URL(s)

### ISSUE THREAD

**Issue by SumanDas94** [slackapi/python-slack-events-api#105]
I verified the challenge parameter using Slack Events API on a paritcular endpoint. 
But whenever I retry on the same endpoint , although it shows that the request is verified but I don't see my nginx logging it. 
Also endpoints which I have used before still show verified even though I removed my slackbot service from them. I am not understanding why this is happening
I am using `slack-bolt==1.1.4`

**Comment by seratch** [comment]
We will answer at https://github.com/slackapi/bolt-python/issues/923
