### ISSUE TITLE
Upgrade the dependent flask version

### ISSUE THREAD

**Issue by theresali-apple** [slackapi/python-slack-events-api#106]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

There is an infinite loop vuln against zipp 3.18.1: https://security.snyk.io/vuln/SNYK-PYTHON-ZIPP-7430899
And there is a package dependency path like: slackeventsapi@3.0.1 > flask@2.3.3 > importlib-metadata@7.1.0 > zipp@3.18.1.
Would you please update the dependency to close the VULN?

#### Reproducible in:
slackeventsapi version: 3.0.1
python version: 3.9
OS version(s): ubuntu 20.04

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

upgrade the dependencies to avoid the VULN.

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
Hi @theresali-apple, thanks for taking the time to report this. A new patch version 3.0.2 resolves this issue: https://github.com/slackapi/python-slack-events-api/releases/tag/v3.0.2

As a side note, we no longer recommend using this library, and a better option is to use bolt-python. Please refer to the important notice on the README (https://github.com/slackapi/python-slack-events-api?tab=readme-ov-file#%EF%B8%8F--important-notice) and consider migrating to bolt-python at your convenience.
