### ISSUE TITLE
Set the bind host via API?

### ISSUE THREAD

**Issue by ssdowd** [slackapi/python-slack-events-api#14]
### Description

I'd like to be able to bind to 0.0.0.0 instead of localhost and I'd rather not have to modify the included module.  Is this documented anywhere?  Without it, you can't really run a slack event listener in a docker container.  At this point I only see a way to change the port.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version:
python version:
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by harmenzon** [comment]
+1 for host='0.0.0.0'

**Comment by Roach** [comment]
Resolved by #20 🎉
