### ISSUE TITLE
Incorrect screenshot in `example/README.rst`

### ISSUE THREAD

**Issue by RyanGladstone** [slackapi/python-slack-events-api#15]
### Description

Excellent library! 

One very minor issue: the screenshot for adding your ngrok url is out of sync with the instructions (example/README.rst)

In the **Subscribe your app to events** section, the text accurately says you should add `/slack/events` to your URL, the screenshot only includes `/events`

https://cloud.githubusercontent.com/assets/32463/24877867/b39d4384-1de5-11e7-9676-9e47ea7db4e7.png

Currently:

![b39d4384-1de5-11e7-9676-9e47ea7db4e7](https://user-images.githubusercontent.com/1573454/30185155-5c1b1c92-93ee-11e7-87b7-228a985461f0.png)

It should look like this:

![challenge_url](https://user-images.githubusercontent.com/1573454/30185162-644d0cb8-93ee-11e7-96af-55fe10d9d5c8.png)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by Roach** [comment]
@RyanGladstone ah, thanks for catching this! I can update it real quick, unless you want to post a PR yo update that image URL?

**Comment by RyanGladstone** [comment]
Please feel free to update it. Thanks!
