### ISSUE TITLE
can the adapter be run as a blueprint instead of as a flask server?

### ISSUE THREAD

**Issue by SachinBhat** [slackapi/python-slack-events-api#19]
### Description

My current event listener was a flask blueprint, while the new adapter is a flask app on its own. I will therefore have to run 2 flask apps now to support the events adapter. Although, running 2 flask apps is possible, sharing data models across the 2 apps becomes difficult and leads to unnecessary complication.

So, wanted to check with you guys if at any point down the line, the adapter abstraction can be simplified? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version:
python version:
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by SachinBhat** [comment]
Chuck it. I figured it out. Fairly straightforward

**Comment by Roach** [comment]
@SachinBhat what'd you end up doing? We're open to making some changes to this library to make this easier if you have ideas.

**Comment by SachinBhat** [comment]
I basically went through your code and replicated it in my app. Bottomline just had to add eventemitter to my blueprint and didnt have to run a new flask app. Maybe you can document this or  build a standalone python code without need for a flask app if you think that might be more useful to users

**Comment by Roach** [comment]
@SachinBhat as a start, I added the ability to bind the adapter to an existing instance of Flask: https://github.com/slackapi/python-slack-events-api/commit/1aac7aca3aebb78b39a7d2772ff8d33c0cb1ff50
