### ISSUE TITLE
Darn - that slash command didn't work (error message: `500_service_error`). Manage the command at slash-command.

### ISSUE THREAD

**Issue by ReenaAcharya** [slackapi/python-slack-events-api#21]
Hi,

I am working on WorkflowMax API. I am integrating WFM with Slack using API gateway and Lambda. I created slash command which invokes API gateway and that in turn invokes Lambda. Simple Lambda Function gets triggered but when I add API calls of WFM I get following error:-
"Darn - that slash command didn't work (error message: `500_service_error`). Manage the command at slash-command."
I am stuck in this issue.
Any suggestions  here would be helpful.

Thanks,
Reena.

**Comment by Roach** [comment]
Do you have access to the error logs? This could be caused be all kinds of things. 🤔
