### ISSUE TITLE
health endpoint

### ISSUE THREAD

**Issue by mike-schiller** [slackapi/python-slack-events-api#24]
### Description

Running a slack events server in Kubernetes requires a liveness / rediness endpoint per: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

As is, this is not natively supported by the server embedded in python-slack-events.

Many other PaaS / Orchestrated environments have similar requirements.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [X ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X ] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version: master
python version: 2.7
OS version(s): Linux Alpine 3.7 based container running in Kubernetes

#### Steps to reproduce:

1. Run this server in Kubernetes

#### Expected result:

Should pass Liveness / Rediness

#### Actual result:

It fails Liveness / Rediness

#### Potential Resolution:
Yes, I can handle this with a reverse proxy in front of this service, but IMO that's a bit kludgey if health is its only purpose. Additionally, that's somewhat error prone as the reverse proxy status would need to be tied to the health of the process running this service.

If you're open to a PR, I can create one from: https://github.com/immuta/python-slack-events-api/tree/health_endpoint

It provides a single default health endpoint at /health and allows users to provide an alternate endpoint and / or a custom health function.

This doesn't currently allow for distinguishing between liveness and readiness, but I can extend it to do so if desired.

**Comment by Roach** [comment]
I'm wondering if this might be a better change to keep inside the app itself, rather than this library. I just posted a patch to make it easier to apply the event listeners to an existing Flask instance, which would make it a viable option to add a health endpoint outside of the lib and still get the same functionality.

https://github.com/slackapi/python-slack-events-api/pull/26

**Comment by mike-schiller** [comment]
I haven't tried it, but that seems better than what I suggested
