### ISSUE TITLE
Groom supported Python versions and declare in setup.py metadata

### ISSUE THREAD

**Issue by aoberoi** [slackapi/python-slack-events-api#47]
### Description

It seems like a bunch of unsupported Python versions are running in the tests. I think it should be the same as those for `slackclient`, which are `py{27,34,35,36}`. This seems to be the cause of failures in open PRs.

Also, declaring the specific versions that are supported in the `setup.py` metadata, [as done in `slackclient`](https://github.com/slackapi/python-slackclient/blob/87630df4665d616b0e294bc888ebb97bdb2300f5/setup.py#L42-L47) would make it easier for users and machines to understand if their system is compatible or not.

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
We've fixed https://github.com/slackapi/python-slack-events-api/issues/53 by merging https://github.com/slackapi/python-slack-events-api/pull/68

As this package depends on Flask, it should align with Flask's policy.

As of Flask [1.1.2](https://pypi.org/project/Flask/1.1.2/), it supports the following versions:
>Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*

I will make a pull request to set the supported versions.
