### ISSUE TITLE
Proposal: Remove Python 2.7.6 support

### ISSUE THREAD

**Issue by Roach** [slackapi/python-slack-events-api#53]
### Description

PR #51 has tests failing because Travis's test runner errors out on 2.7..6: https://travis-ci.org/slackapi/python-slack-events-api/jobs/529462763

I submitted a PR to simply remove the 2.7..6 environment from the travis configs, but closed it when I remembered that we have specific request signing logic for Python 2.7..6:
https://github.com/slackapi/python-slack-events-api/blob/master/slackeventsapi/server.py#L47-L83

2.7..6 was released in 2013, and PSF actively recommends 2.7.15 for new downloads: https://www.python.org/download/releases/2.7/

I'd like to remove the custom logic and test config for 2.7.6.

**Comment by vvatelot** [comment]
Same for all current PR...
All failing with 2.7.6 python version, except for a PR that passed the tests 12 months ago.

**Comment by vvatelot** [comment]
#59

**Comment by alperkal** [comment]
Any decisions here?

**Comment by seratch** [comment]
👋 I think there is no objection here. I will move this forward and check the PRs blocked by this.
