### ISSUE TITLE
Missing example usage with flask app factory pattern

### ISSUE THREAD

**Issue by Ambro17** [slackapi/python-slack-events-api#55]
### Description

There's no example on how to register the server as a blueprint that would then be added to a flask app. Is it possible?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version: 2.1.0
python version: 3.6.0
OS version(s): Ubuntu 18

#### Steps to reproduce:

1. Try to use app factory pattern and create a blueprint for slackevents that is not yet asociated with any app
2. Try to add it
3. Fail because there's no example on the docs

#### Expected result:

Documentation on whether this approach is supported or not

#### Actual result:

No relevant documentation

**Comment by seratch** [comment]
A recent pull request #69 (based on #56) has added support for this. Now developers can find a simple example [here](https://github.com/slackapi/python-slack-events-api/tree/master/example/blueprint). This feature will be available since 2.2.0. I will be releasing the new version early next week. 

Let me close this issue.
