### ISSUE TITLE
handling Request URL for interactive messages

### ISSUE THREAD

**Issue by hkhrais** [slackapi/python-slack-events-api#65]
### Description
While reading [your example](https://slack.dev/python-slackclient/basic_usage.html#opening-a-modal
) you have used verify_request() to verify the signature, this function does not exist in python-slack-events-api repo. 

Is there a way to use python-slack-events-api to handle request URL for interactive messages (like button clicks) or do i need to build the [low level verification](https://github.com/slackapi/python-slack-events-api/blob/master/slackeventsapi/server.py#L47) on my own? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [ X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ X] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version:
python version:
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
@hkhrais 
Thanks for asking this question! Unfortunately, we don't provide any official tools to handle user interactions (button click, select menu, modals, home tab etc) yet. However, in the near future (I cannot tell the date to ship it yet but at least within a few months), we'll come up with a comprehensive toolkit for Python developers. Until then, please do the request verification and payload handing on your own 🙇

**Comment by dinvlad** [comment]
FWIW here's a sample implementation: https://gist.github.com/dinvlad/cb2c3e8c8cd7905b832f38db92308c64

**Comment by seratch** [comment]
FYI: slackclient PyPI package supports request verification since v2.6.0
https://github.com/slackapi/python-slackclient/pull/686

**Comment by dinvlad** [comment]
Ok, thanks! It turns out our `slackclient` was not updated, so I haven't seen this method there. I also found another one, `slack.validate_slack_signature()`, which is more low-level.

**Comment by seratch** [comment]
Bolt for Python is almost ready for GA release sometime soon. Try the new library out and let us know your feedback!
* https://github.com/slackapi/bolt-python
* https://slack.dev/bolt-python/concepts#basic
