### ISSUE TITLE
Passing Flask app proxy as server

### ISSUE THREAD

**Issue by tstoco** [slackapi/python-slack-events-api#66]
Hi Guys,

I have an app factory on my setup and the app object usually it is invoked as :
`from flask import current_app as app`

However, the slackeventsapi complains about the app object : 
`TypeError("Server must be an instance of Flask")`

I have fixed adding the following to server.py : 

`from werkzeug.local import LocalProxy # Importing the localproxy class`

Line 25 
  Changed from : 
   ` if isinstance(server, Flask):`
  to :
    `if isinstance(server, Flask) or isinstance(server, LocalProxy):`

Basically, if a Flask app proxy is passed the api will carry on without complaining since it has the same methods as the Flask app object.

I hope this help other people and it is considered as a solution if more information is needed I am help to provide. 

Thanks for the good work with the API.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug ?
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:
slackeventsapi version: slackeventsapi==2.1.0
python version: Python 3.7.3
OS version(s):

**Comment by seratch** [comment]
@tstoco Thanks for reporting this. I just shipped 2.2.0rc1, a pre-release version including a fix for this. Please try it out if you have a chance. v2.2.0 will be out soon.
