### ISSUE TITLE
API for verifying Signature?

### ISSUE THREAD

**Issue by devanshbatra04** [slackapi/python-slack-events-api#67]
### Description

The module verifies requests using verification token. Does it support Signing Secret based verification? I couldn't find it by going through the docs although I do see it's occurences in the code. 

To be more specific, I want to be able to verify requests from slack using the signing secret in my flask app but not just for Events requests. I have already written my app.
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version:
python version:
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
This module supports signature verification. Refer to [the usage guide](https://github.com/slackapi/python-slack-events-api#--usage) and [the implementation](https://github.com/slackapi/python-slack-events-api/blob/v2.1.0/slackeventsapi/server.py#L103-L106)

**Comment by devanshbatra04** [comment]
Thank you for the prompt response. I needed the implementation location so I can implement a similar function for all my routes which include Slash Commands and Interactions. Closing the issue.
