### ISSUE TITLE
Not getting channel events except "at mention" events

### ISSUE THREAD

**Issue by rcsrao** [slackapi/python-slack-events-api#78]
We have below permissions set for our app and for the past few hours we are not getting any events which we have posted on the channel except "at mention" events. Anything changed?  

Also direct messages to app working without at mention. 

```

Event Name | Description | Required Scope
app_mention | Subscribe to only the message events that mention your app or bot | app_mentions:read |  
message.channels | A message was posted to a channel | channels:history |  
message.im | A message was posted in a direct message channel | im:history

```

**Comment by seratch** [comment]
@rcsrao Have you invited your app's bot user to the channels? For direct messages, a bot user cannot receive message events in a channel the bot use is not a member of.

**Comment by rcsrao** [comment]
@seratch Yeah, bot is already a member of channel already and it was working till a few hours before.

**Comment by rcsrao** [comment]
It'started working again! Must be something changed on Slack end!

**Comment by seratch** [comment]
The weird behavior on the Slack side is not good but I'm glad to know your issue has been resolved.
