### ISSUE TITLE
Should add the required bot events for the example program

### ISSUE THREAD

**Issue by Hippocrates** [slackapi/python-slack-events-api#81]
The example program and instructions provided were very helpful, however they do not mention anything about the reaction_added event that the user needs to subscribe to in order to make the example work properly with the emoji reaction (in this case, it should mention _both_ message.channels and reaction_added). It didn't take me too long to figure it out, but I could see this being an unneeded source of frustration.

It seems that this is along the same lines as issue #64, however the user closed the issue once they figured it out. I think just a small addition of an image (and mentioning the other permissions) would prevent further repeats of this issue.

![BotSubscribe](https://user-images.githubusercontent.com/164546/97811582-609f6980-1c30-11eb-8e2a-861109b46bde.png)

**Comment by seratch** [comment]
Fixed by #82 - thanks for your contribution!
