### ISSUE TITLE
message.app_home event

### ISSUE THREAD

**Issue by JoshuaBrand** [slackapi/python-slack-events-api#85]
### Description

Following the [message example](https://github.com/slackapi/python-slack-events-api/blob/main/example/example.py#L14-L21), when sending a direct message to an App, the [message](https://api.slack.com/events/message) event type is showing the `channel_type` as [im](https://api.slack.com/events/message.im) instead of [app_home](https://api.slack.com/events/message.app_home).

### What type of issue is this?
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [x] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:
slackeventsapi version: `2.2.1`
python version: `3.9.1`
OS version(s): `macOS 11.01`

#### Steps to reproduce:

1. Per [message.app_home](https://api.slack.com/events/message.app_home), subscribe to [app_home_opened](https://api.slack.com/events/app_home_opened) and [message.im](https://api.slack.com/events/message.im) event(s) for the [ngrok](https://api.slack.com/tutorials/tunneling-with-ngrok) `/slack/events` URL.
2. Have your App `print` incoming events. (See the example attached below.)
3. In Slack, send a direct message to your App consisting of the string `hi`.

#### Expected result:

Per [this article](https://api.slack.com/changelog/2018-05-app-home-events-for-workspace-apps), when sending a direct message to an App, `channel_type` should be [app_home](https://api.slack.com/events/message.app_home) instead of [im](https://api.slack.com/events/message.im).

#### Actual result:

Example of received event(s):
```
{
    "client_msg_id": "5c4a5cb4-dd2f-4dd0-ab2d-c960079d3a64",
    "type": "message",
    "text": "hi",
    "user": "U01FA1X7WBV",
    "ts": "1610743774.093000",
    "team": "T01FNECMMT3",
    "blocks": [
        {
            "type": "rich_text",
            "block_id": "0fso1",
            "elements": [
                {
                    "type": "rich_text_section",
                    "elements": [
                        {
                            "type": "text",
                            "text": "hi"
                        }
                    ]
                }
            ]
        }
    ],
    "channel": "D01HHS5V71A",
    "event_ts": "1610743774.093000",
    "channel_type": "im"
}
```
```
{
    "bot_id": "B01J1GQHGMN",
    "type": "message",
    "text": "Hello",
    "user": "U01HQAGQLJV",
    "ts": "1610743775.093100",
    "team": "T01FNECMMT3",
    "bot_profile": {
        "id": "B01J1GQHGMN",
        "deleted": false,
        "name": "test",
        "updated": 1608525077,
        "app_id": "A01HHS177E0",
        "icons": {
            "image_72": "https://avatars.slack-edge.com/2020-12-20/1589929255555_7550dbf394f22892292b_72.png"
        },
        "team_id": "T01FNECMMT3"
    },
    "channel": "D01HHS5V71A",
    "event_ts": "1610743775.093100",
    "channel_type": "im"
}
```

#### Attachments:

App code to reproduce the issue:
```
#!/usr/local/bin/python3

from slackeventsapi import SlackEventAdapter
from slack_sdk import WebClient
import json
import os

# App Credentials
secret = os.environ['TEST_SECRET']
slack_events_adapter = SlackEventAdapter(secret, "/slack/events")

# Instantiating Slack Client
client = WebClient(token=os.environ['TEST_TOKEN'])

# Slack Message
@slack_events_adapter.on("message")
def handle_message(event_data):
    message = event_data["event"]
    # Print Event(s)
    print(json.dumps(message, indent=4))

    # If the incoming message contains "hi", then respond with a "Hello" message
    if message.get("subtype") is None and "hi" in message.get('text'):
        channel_id = message["channel"]
        message = "Hello" % message
        client.chat_postMessage(channel=channel_id, text=message)

# Server Port 8242
slack_events_adapter.start(port=8242)

```

**Comment by seratch** [comment]
Hello @JoshuaBrand, thanks for taking the time to ask this question! And I do understand this is confusing.

>Developer preview has ended
>This feature was exclusive to our workspace apps developer preview. The preview has now ended, but fan-favorite features such as token rotation and the Conversations API will become available to classic Slack apps over the coming months.

As mentioned in the page https://api.slack.com/changelog/2018-05-app-home-events-for-workspace-apps , this subtype was introduced as part of beta program for "workspace apps". After the beta, this subtype was not applied to all apps.

Your understanding here is correct. Only "im" subtype can be sent in this scenario.

**Comment by seratch** [comment]
Let us know if you have anything further to ask/discuss here. I will close this issue after waiting for your response for a while.

**Comment by JoshuaBrand** [comment]
@seratch thank you for the explanation, this can be resolved.
