### ISSUE TITLE
Is it possible to create a link to the thread from a event message?

### ISSUE THREAD

**Issue by bartier** [slackapi/python-slack-events-api#86]
### Description

Hello there!

Let's assume the function below that receives message events:
```
...
@slack_events_adapter.on("message")
def func(event_data):
   ...
...
``` 

I'd like to know if it is currently possible to create a thread link (same as we get from the image button bellow), based on the **event_data** I receive from the message event:
![image](https://user-images.githubusercontent.com/18057391/107557371-47577300-6bb8-11eb-89a7-3c50d15811cf.png)

The link is generated as the example: https://`your_workspace`.slack.com/archives/`channel_id`/`msg_id`

Real life example: `https://workspace.slack.com/archives/CR3SUPEMU/p1234567891234561`

As far as I know, [I got only the `channel property id`  from the Slack API](https://api.slack.com/events/message), and I couldn't find a reference to the `msg_id` I'd need to create a correct link.

I'm not sure if I'm missing something... Is there any alternatives to that?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@bartier You can use https://api.slack.com/methods/chat.getPermalink for this!

**Comment by bartier** [comment]
@seratch Thanks! I'll close this issue then.
