### ISSUE TITLE
Is there any API that exists to know if the message is deleted in the channel?

### ISSUE THREAD

**Issue by rcsrao** [slackapi/python-slack-events-api#87]
Is there any API that exists to know if the message is deleted in the channel?

**Comment by seratch** [comment]
@rcsrao There is no web api for this. You can subscribe to message events and know deletion event with the ones that have subtype: message_deleted. https://api.slack.com/events/message/message_deleted

**Comment by rcsrao** [comment]
We have a bot to respond messages in the channel as threads and sometimes users are deleting messages before Bot responds to that message. Further Bot is throwing that message in the channel directly (intend is to reply in the thread only) since the parent message doesn't exist anymore. 
We would like to stop this behavior.

**Comment by seratch** [comment]
You can use https://api.slack.com/methods/conversations.history with inclusive=1&limit=1&oldest={the user message's ts} before posting the bot's reply (or right after posting the reply). If the original message no longer exists, your app has to delete (or cancel to post) its reply. Ultimately, this is a kind of race condition issue. Thus, I think there is no simple solution for it.

**Comment by rcsrao** [comment]
Yeah, I tried that but API is saying it still exists, 

{'ok': True, 'latest': '1613716911.001000', 'messages': [{'client_msg_id': '****', 'type': 'message', 'text': 'fit', 'user': '****', 'ts': '1613716836.000800', 'team': '****', 'blocks': [{'type': 'rich_text', 'block_id': 'jOde', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'fit'}]}]}]}], 'has_more': True, 'pin_count': 0, 'channel_actions_ts': None, 'channel_actions_count': 0, 'response_metadata': {'next_cursor': '*****'}}

**Comment by rcsrao** [comment]
Never mind, it worked. I was using latest.

{
            "channel": channel,
            "oldest": thread_ts,
            "inclusive": 1,
            "limit": 1
            }


Thanks @seratch
