### ISSUE TITLE
Question: Could Slack provide IP range to restrict the request URL access from anonymous 

### ISSUE THREAD

**Issue by rcsrao** [slackapi/python-slack-events-api#92]
Question: Could Slack provide IP range to restrict the request URL access from anonymous

**Comment by seratch** [comment]
@rcsrao Unfortunately, the Slack server-side does not provide the information (actually static address range is not guaranteed).

> restrict the request URL access from anonymous

To do this, we recommend validating `x-slack-signature` and so forth. As you may know, this library does that for you. https://api.slack.com/authentication/verifying-requests-from-slack

By the way, I'd recommend joining our [Slack Developer Community workspace](https://join.slack.com/t/community/shared_invite/enQtNzYxNzM5NzU0Mzg3LWFhZjE3ZjY1M2JhM2MzNGNmMmE0Zjc4Y2E5NDc2NGJiODAxNDMzN2Y1MjVlYWU3ZGVlYzhlMDVhNzA0Nzg1OGY) and asking this kind of question there. You will be able to get help from more people in the community.

As I've provided an answer to this question, let me close this issue now.
