### ISSUE TITLE
slackeventsapi.server.SlackEventAdapterException: Invalid request timestamp

### ISSUE THREAD

**Issue by hashimjd** [slackapi/python-slack-events-api#94]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version:
python version:
OS version(s):

#### Steps to reproduce:

1. Make a post request through POSTMAN to the slack_event_adapter to replicate sending a message through channel
2. The json component of the request is given below which is sent as a "Pre-request Script".

#### Expected result:

The expected result was that the request would be parsed by my application and dealt accordingly.

#### Actual result:

I run into an error saying "slackeventsapi.server.SlackEventAdapterException: Invalid request timestamp" despite having HTTP_X_SLACK_REQUEST_TIMESTAMP configured and this is set dynamically to ensure that the timestamp is of the time when the request is sent. This is highlighted in the screenshot below.
<img width="1067" alt="Screen Shot 2021-05-14 at 11 42 23 AM" src="https://user-images.githubusercontent.com/42841404/118315162-01a59180-b4aa-11eb-86c8-e028d7de41ce.png">
<img width="1328" alt="Screen Shot 2021-05-14 at 11 43 57 AM" src="https://user-images.githubusercontent.com/42841404/118315183-08340900-b4aa-11eb-85c5-99e6f6ed2184.png">

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mwbrooks** [comment]
Hi @hashimjd 👋🏻 Thanks for the detailed issue, including the screenshots!

It looks like the expected [header is `X-Slack-Request-Timestamp`](https://github.com/slackapi/python-slack-events-api/blob/d2213d8cad9ba5a930bfd50dacdf9f44c25943d7/slackeventsapi/server.py#L91). In the sample above, it looks like Postman is setting `HTTP_X_SLACK_REQUEST_TIMESTAMP`.

Can you try updating the header to be `X-Slack-Request-Timestamp`? (Case sensitivity should not matter)

Please let me know how that goes!
Michael

**Comment by hashimjd** [comment]
I tried doing that but the problem still persists. I've attached a screenshot below that demonstrates the issue. In the server section, the issue still is "slackeventsapi.server.SlackEventAdapterException: Invalid request timestamp"

<img width="1007" alt="Screen Shot 2021-05-17 at 9 21 52 AM" src="https://user-images.githubusercontent.com/42841404/118522940-7a4a5f00-b6f1-11eb-9389-a78362dbfc78.png">

**Comment by seratch** [comment]
You may no longer be working on this but if you dynamically set the x-slack-request-timestamp value, the x-slack-signature value must be also updated using the timestamp value. Thus, this is an expected behavior (= this library correctly detects invalid x-slack- header values in this scenario)

I hope this helps.
