### ISSUE TITLE
itsdangerous package conflict with latest version of flask

### ISSUE THREAD

**Issue by owensilk** [slackapi/python-slack-events-api#95]
### Description

The latest version of Flask (2.0.1) released on `2021-05-21` requires `itsdangerous>=2.0` this package required `itsdangerous<2` can this be safely changed so we can install the latest version of Flask

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version: `2.2.1`
python version: 3.7
OS version(s): Mac OS 10.15.7

#### Steps to reproduce:

1. Using Pipenv for depency resolution. `pipenv install flask slackeventsapi`
2. 

#### Actual result:

```
Resolving dependencies...
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches itsdangerous<2,>=2.0 (from slackeventsapi==2.2.1->-r /var/folders/l2/z3fcfqdn6g56xqzyp36r6yyc0000gq/T/pipenv9_syt5ffrequirements/pipenv-4_xicpka-constraints.txt (line 14))
Tried: 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 1.1.0, 1.1.0, 2.0.0, 2.0.0, 2.0.1, 2.0.1
Skipped pre-versions: 2.0.0a1, 2.0.0a1, 2.0.0rc1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc2
There are incompatible versions in the resolved dependencies:
  itsdangerous<2 (from slackeventsapi==2.2.1->-r /var/folders/l2/z3fcfqdn6g56xqzyp36r6yyc0000gq/T/pipenv9_syt5ffrequirements/pipenv-4_xicpka-constraints.txt (line 14))
  itsdangerous>=2.0 (from flask==2.0.1->-r /var/folders/l2/z3fcfqdn6g56xqzyp36r6yyc0000gq/T/pipenv9_syt5ffrequirements/pipenv-4_xicpka-constraints.txt (line 6))
```

**Comment by seratch** [comment]
Hi @owensilk, thanks for taking the time to write in!

Interestingly, the latest version of this package still supports Python 2.7 in addition to 3.x. 
* https://github.com/slackapi/python-slack-events-api/blob/v2.2.1/setup.py#L53
* https://github.com/slackapi/python-slack-events-api/blob/v2.2.1/setup.py#L41-L43

For this reason, we intentionally set the upper limit of the major version of `itsdangerous` for Python 2.7 compatibility.

As Python 2 is already flagged as EOLed, it should be reasonable enough to stop supporting Python 2.7. To move this forward, I'm thinking that the following steps would be the smoothest:
* Start 3.x development with the `main` branch, which supports only Python 3.x and Flask 2.x
* Cut off `2.x` branch for maintenance releases of v2.2.x

We are a bit busy for other projects this week. I will start working on this transition early next week.

Thanks again for pointing this out 👍

**Comment by seratch** [comment]
Created the `v2` branch. If you want to contribute to v2 series, please send pull requests toward the branch.

TODO: update https://github.com/slackapi/python-slack-events-api/blob/main/.github/contributing.md
